# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: databus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import invoker.databus.gogo_pb2 as gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='databus.proto',
  package='infra.databus',
  syntax='proto3',
  serialized_options=_b('Z\007databus'),
  serialized_pb=_b('\n\rdatabus.proto\x12\rinfra.databus\x1a\ngogo.proto\"~\n\x06Header\x12\x43\n\x08metadata\x18\x01 \x03(\x0b\x32#.infra.databus.Header.MetadataEntryB\x0c\xea\xde\x1f\x08metadata\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xca\x02\n\tMessagePB\x12\x14\n\x03key\x18\x01 \x01(\tB\x07\xea\xde\x1f\x03key\x12\x34\n\x05value\x18\x02 \x01(\x0c\x42%\xea\xde\x1f\x05value\xfa\xde\x1f\x18\x65ncoding/json.RawMessage\x12\x18\n\x05topic\x18\x03 \x01(\tB\t\xea\xde\x1f\x05topic\x12 \n\tpartition\x18\x04 \x01(\x05\x42\r\xea\xde\x1f\tpartition\x12\x1a\n\x06offset\x18\x05 \x01(\x03\x42\n\xea\xde\x1f\x06offset\x12 \n\ttimestamp\x18\x06 \x01(\x03\x42\r\xea\xde\x1f\ttimestamp\x12\x46\n\x08metadata\x18\x07 \x03(\x0b\x32&.infra.databus.MessagePB.MetadataEntryB\x0c\xea\xde\x1f\x08metadata\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\tZ\x07\x64\x61tabusb\x06proto3')
  ,
  dependencies=[gogo__pb2.DESCRIPTOR,])




_HEADER_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='infra.databus.Header.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='infra.databus.Header.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='infra.databus.Header.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=170,
)

_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='infra.databus.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata', full_name='infra.databus.Header.metadata', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\352\336\037\010metadata'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_HEADER_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=170,
)


_MESSAGEPB_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='infra.databus.MessagePB.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='infra.databus.MessagePB.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='infra.databus.MessagePB.MetadataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=170,
)

_MESSAGEPB = _descriptor.Descriptor(
  name='MessagePB',
  full_name='infra.databus.MessagePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='infra.databus.MessagePB.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\352\336\037\003key'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='infra.databus.MessagePB.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\352\336\037\005value\372\336\037\030encoding/json.RawMessage'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic', full_name='infra.databus.MessagePB.topic', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\352\336\037\005topic'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partition', full_name='infra.databus.MessagePB.partition', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\352\336\037\tpartition'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='infra.databus.MessagePB.offset', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\352\336\037\006offset'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='infra.databus.MessagePB.timestamp', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\352\336\037\ttimestamp'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='infra.databus.MessagePB.metadata', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\352\336\037\010metadata'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGEPB_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=503,
)

_HEADER_METADATAENTRY.containing_type = _HEADER
_HEADER.fields_by_name['metadata'].message_type = _HEADER_METADATAENTRY
_MESSAGEPB_METADATAENTRY.containing_type = _MESSAGEPB
_MESSAGEPB.fields_by_name['metadata'].message_type = _MESSAGEPB_METADATAENTRY
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['MessagePB'] = _MESSAGEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _HEADER_METADATAENTRY,
    '__module__' : 'databus_pb2'
    # @@protoc_insertion_point(class_scope:infra.databus.Header.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'databus_pb2'
  # @@protoc_insertion_point(class_scope:infra.databus.Header)
  })
_sym_db.RegisterMessage(Header)
_sym_db.RegisterMessage(Header.MetadataEntry)

MessagePB = _reflection.GeneratedProtocolMessageType('MessagePB', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _MESSAGEPB_METADATAENTRY,
    '__module__' : 'databus_pb2'
    # @@protoc_insertion_point(class_scope:infra.databus.MessagePB.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _MESSAGEPB,
  '__module__' : 'databus_pb2'
  # @@protoc_insertion_point(class_scope:infra.databus.MessagePB)
  })
_sym_db.RegisterMessage(MessagePB)
_sym_db.RegisterMessage(MessagePB.MetadataEntry)


DESCRIPTOR._options = None
_HEADER_METADATAENTRY._options = None
_HEADER.fields_by_name['metadata']._options = None
_MESSAGEPB_METADATAENTRY._options = None
_MESSAGEPB.fields_by_name['key']._options = None
_MESSAGEPB.fields_by_name['value']._options = None
_MESSAGEPB.fields_by_name['topic']._options = None
_MESSAGEPB.fields_by_name['partition']._options = None
_MESSAGEPB.fields_by_name['offset']._options = None
_MESSAGEPB.fields_by_name['timestamp']._options = None
_MESSAGEPB.fields_by_name['metadata']._options = None
# @@protoc_insertion_point(module_scope)
